app.google-client-id=765195060920-27lfkdb7ue85bvahjm05n491rkjmsu1r.apps.googleusercontent.com
app.expose-dev-otp=true
spring.datasource.url=jdbc:h2:mem:jukebox;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
